(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// stage content:
(lib.animation = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// car
	this.instance = new lib.car();
	this.instance.setTransform(-111,253.7,1,1,0,0,0,110,46.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:509},347).wait(1));

	// bg
	this.instance_1 = new lib.bg();
	this.instance_1.setTransform(200,150,1,1,0,0,0,200,150);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1}]}).wait(348));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-391.4,0,791.5,507.3);


// symbols:
(lib.car = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#73AEA8").s().p("AM0B0IgHgMIhLh/IiqAAIghA0IgwA+IgFAAIhFAAIAYg8IAwh2IE7AAIAsBrIAnBggAnQBXIgPg9IgwhCIjNgDIg/BrIgSAfIhFAAIA1hRIBNiBIEEAJIBPCFIAbBIIhKACg");
	this.shape.setTransform(107.1,67.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#97583E").s().p("AIKBjQgugugChAIAFAAIAwg9IAhg2ICqAAIBLB/QgGA4gpAqQgxAwhFAAQhFAAgxgwgAJWg7QgRARAAAYQAAAXARARQARARAYAAQAZAAARgRQARgRAAgXQAAgYgRgRQgRgRgZAAQgYAAgRARgAr0BjQgwgxAAhDIABgUIA/htIDNACIAwBEIAPA+QgBBBgvAwQgxAwhFAAQhFAAgxgwgAqog7QgRARAAAYQAAAXARARQARARAYAAQAZAAARgRQARgRAAgXQAAgYgRgRQgRgRgZAAQgYAAgRARg");
	this.shape_1.setTransform(107.9,77.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#0188A9").s().p("AiDBoIAAgDIg1AAQhrABhuAAIgogBIhPiFIkDgIIhNCBIhugGIAAAAIAAgBIBPi1ILAgGIAAAAIA0gBIAAAJIRKAYIghCiIh2AFIgshrIk7AAIgwB2Qh4ACh4AAQiXAAiVgDg");
	this.shape_2.setTransform(109.9,60.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#0099CC").s().p("AO+gMIxKgYIAAgJIg0AAIAAABIrBAGIhOC1IAAAAQgdgEgeAAIgfj3QCugQCrgKQCxgLGTgEIBcACIAmABQFVAFFVASQDGAKDEAOIgMA+IgVBxIgMBFIhgAFg");
	this.shape_3.setTransform(110.8,54.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(148,210,252,0.443)").s().p("AgRCoIgClgIGeAMIDcFmgApmCaIB+lEIFxgMIAAgBIAzgCIAAADIAOgBIgBFeg");
	this.shape_4.setTransform(106.6,19.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("ANPFDIAVhzIAnAAIAABzgAjEBjIgmgBIhcgBQmTADixAMICVmlIGagLIAAgBIAzgBIHwAEIEeG5QlVgSlVgGgAj1BHIJ4ARIjclmImegLgAlbkYIAAAAIlxAMIh+FEIIvAOIABleIgOAAIAAgCg");
	this.shape_5.setTransform(129.4,29.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#B3B3B3").s().p("AJWApQgRgRAAgYQAAgXARgRQARgRAYAAQAZAAARARQARARAAAXQAAAYgRARQgRARgZAAQgYAAgRgRgAqoApQgRgRAAgYQAAgXARgRQARgRAYAAQAZAAARARQARARAAAXQAAAYgRARQgRARgZAAQgYAAgRgRg");
	this.shape_6.setTransform(107.9,76);

	this.addChild(this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(4.2,-2.9,216,95.7);


(lib.bg = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EAEAEA").s().p("AAAAAIAAAAIABAAg");
	this.shape.setTransform(108.2,153.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E0E0E0").s().p("AG+C8QgUgRgLgVQgcANghAAQg6AAgpgmQgqgnAAg4QAAgRAFgOIAAAAQAAA0ApAnQApAnA6AAQAhAAAcglQALAtAVARQAUARAZAKIgnAQIgLgJgANoCfIAIgFQAbgUAAgOQAAgPAgAUQAWANAYgJIgSApQgQAFgTACQgegLgegHgAKdCEIAMAJIgMABIAAgKgArwBYQgUgRgLgVQgcANghAAQg7AAgogmQgpgmgBg3QAAgRAEgQIABAAQAAA3ApAmQApAlA6AAQAhAAAdgjQALArATARQAuAmA+AAQA/AAAsgmQADgCACgUQAxApA/AAQBIAAAagTQAbgUAAgOQAAgPAgAUQAgATAkgbQATgNAJgPIADACQAAAjgkAaQgkAagzAAIgKAAIgCAAIgYgFQgdAihIAAQhAAAgxgXIgEAEQgtAmg+AAQg/AAgtgmgAHsgbQCMBPCKhMQhBBEhEAAQhGAAhLhHgAibgrQAAgPgFgNQArgDAhh6IADABQgfCGgqAUgArCh/QCMBRCLhOQhCBGhEAAQhGAAhLhJg");
	this.shape_1.setTransform(116.6,172.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FB9837").s().p("AztCzQHFg9HBiSQDrhPDzBEQB3hrB7g3IAmgQQBWggBXgHIANgBQBegGBgAYQAeAIAfAKIAbAKIgdBGQlUh0k7D5QEwC2CVBKQiRg6lwiXQjzhCjrBNQnBCUnFA9gASsiEIgjgGIBlADIgMAGQgaAAgcgDg");
	this.shape_2.setTransform(126.3,212.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AGzDNQgUgRgLgtQgcAlghAAQg6AAgpgnQgqgnAAg2IAAAAIAAgDQAGgRAJgOQAJgOANgKQApgnA6AAQAfAAAbAMQAMgQAQgOQBHhABlAAQBkAABIBAQAKAJAJAtQArgcAgAfQAPAMAKATIASAKQARAKALAMQAOADANAFQAJACAJAAQAIAfALAdIgbA5QgZAJgWgNQgfgUAAAPQgBAOgaAUIgJAFQhggYheAGIgMgJIgBAKQhXAGhWAhQgYgKgVgRgALzAZQiLBOiLhRQCSCPCEiMgAr7BpQgUgRgLgtQgcAlghAAQg7AAgognQgpgmgBg1IAAAAIAAgDQAFgQALgPQAIgOANgMQApgnA6AAQAfAAAbAMQAMgQAQgOQBHhABlAAQBlAABHBAQAKAJAJAtQArgcAgAfQAPAOAKATIASAKQAQAKAMAMQAOADANAFQBNARA9h9QggB6gsADQAGANAAANIABACIgBABIgLACQAEAKABALIAAAIIgCgCQgJARgTANQglAbgggTQgfgUAAAPQAAAOgbAUQgaAThIAAQg/AAgygpQgCAUgCACQgsAmg/AAQg/AAgtgmgAm7hJQiLBMiLhPQCSCNCEiKgAhkiRIAGgOIgCAPg");
	this.shape_3.setTransform(118.2,167.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["#C0CA00","#FF3737"],[0,1],-135.6,84.5,-133.3,-80.8).s().p("AdUINIgFhIQBEgDA8gMIAABXgAYRINIgGhjQA8ALA4AHIgIBRgAKjINIgLi+QCXgHB2grQCmgVAkhhIAyAGIgjFggA/PINIAApiQHGg+HAiUQDrhOD2BEQFwCXCRA5QiVhKkxi4QE8j4FRBzQhkD9gqD6QgDA9ALAuIACAAIgBAEQAIAlASAdIACAAIgBACQAvBPB0AEQCEAfB2APIgTDKgAINnhIBsADIAAAAIhRABQgTACgVAAIANgGg");
	this.shape_4.setTransform(200,247.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#E44407").s().p("AImD9IAIhRIAEgqIAFgzIA+ABQALAGAJALQADADAEACQAMAGAJAPQAFAHAGAGQADADAAADQACAJAMACQABAAACAFQAOAfgCAkIgBAcgAAtD9IAjleIAHhGIAIhVIBoADQAQAIAPAQQgUBMgNBNQgCAwAIAkIACgBIgBAEQAHAdANAXIADAAIgCABQAmA9BWAGIACAuIABAeIACAqgArQD9IAUjKIAFgzIAGhAIBOADQAOAGALAOQADAEAGADQAOAHAMASQAGAJAHAFQAEAEABAEQACAMAPADQABAAADAGQARAmgCAuQgDBDADBEg");
	this.shape_5.setTransform(310.5,274.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#A93205").s().p("AKAD8IABgcQABgkgOgfQgCgFgBAAQgMgCgBgKQgBgDgDgDQgGgGgEgHQgKgOgLgHQgFgCgCgDQgKgLgKgFICDAEIABAVIAFBMIAEBIgAESD8IgCgrIgBgeIgBgtIAJAAQAqAKApAIIAGBkgApAD8QgEhEAEhEQACgtgSgnQgDgGgBAAQgOgCgDgMQAAgEgEgEQgIgGgFgIQgMgSgOgIQgGgDgDgEQgMgNgNgHICkAFIACAaIAFBdIAMC/gAB3j7IAlACIgGAWQgOgQgRgIg");
	this.shape_6.setTransform(318.5,274.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#6CD801").s().p("AJ8EiIACgBQAcAlgXAsIgDAFQgugkAqgxgAqNBOQgBgbAageIADgBQAdAogPAtIgIAQQgBAEgDACQgdgXgBgagACNl1IAEgBQAuA+gmBJQgCAEgEAEQhMg8BGhSg");
	this.shape_7.setTransform(300.2,204);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#57AD01").s().p("AF1NdQAFgNAMgOIACgBQAbAkgUApIgCAEQgBACgCACQghgZAMgggAh6NSQgTgdATgiQAFgLAKgLIADgBQALAOAFAPQAJAegOAhIgFAJIgEAGQgNgKgHgLgAOtK4IACgBIAGAJIAABHIAAABIgEAFQgugkAqgxgAJXLwQgLgQAFgTQAEgPAPgSIACgBQAOATABAVQABAOgFAQIgGALIgEAFQgKgIgGgJgAubJ2IACgBQAjAvgcA2QgCADgDADQg5gtA1g9gAj0HWIAKgMIADgBQAFAHAEAIQAVAogYAuIgEAFQg0goAlg1gAqGG7IACgBQAjAugcA3IgFAGQg5gtA1g9gABoCKQAIgWAVgYQAAAAAAAAQABgBAAAAQABAAAAAAQABAAAAAAQAWAdADAfQAEAkgUAmQgCAFgEADQg2gqATg1gAJ6BRIACgCIACAAIAAABQAcAkgXArIgEAFQgsgkAngvgApok4IACgBQAjAvgcA2IgFAGQg5gtA1g9gACtuUIADgBQAvA+gmBIQgCAEgEAEQhMg8BGhRg");
	this.shape_8.setTransform(305,175.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#76EB01").s().p("AJ8HnIACgBQAcAlgXArIgDAFQgugkAqgwgAp0BHIADgBQAjAugdA2QgBAEgDADQg5guA0g8gACNo5IAEgBQAuA+gmBIQgCAEgEAEQhMg8BGhRg");
	this.shape_9.setTransform(300.2,125.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#97FE30").s().p("ALhS4QgpgJgqgJIgJgBQhXgHglg8IABgBIgCgBQgOgWgHgeIACgDIgDABQgIgmACgxQANhMAUhNIAGgWQAMguAPgtQAuiOBGiOQgXg9gFg+QgDgoAFgnQANhwBJhwQAigvAigiQgcAtgIAwIgDANQgFAggMAcQgCAGgHAIQgHAIgQAFQgRAGgVA7QgLAfAHAdQAGAbAUAZQAbAhAKAhQAGAWgBAVQgCA5g9BFQg8BGAPAeQAQAfAHAKQAIAKgCADQgHAPgFATIgDANIgDANQgGAWgMAZIgIARIgBABIgKASQgQAZgPAaIgWAnIgIARIgPAlIgCAFIgCAGIABAAQgSBvBVAoIgBACIAHABQAUAEAYAIIAEABIALADQAaALAdAFIAVADIAaAGQANADAMACQAkADAkABIgFArQg4gIg8gKgAqOQjQh1gFgxhOIACgCIgDAAQgSgdgIglIABgFIgCABQgLgvADg8QAqj9Bnj8IAdhGIAIgRIASgoIAbg5QgMgegHgeQg9jqCcjtQAqg8AqgsQgiA4gLA/IgDAQQgGAogQAjQgDAHgIAKQgJALgUAHQgUAGgbBKQgbBKA3BDQAXAdANAcIAHARIAEAPQAGAXgBAXQgDBFhLBXIgKANQgeAjgMAbQgPAgAKATQATAnAKAMQAJAMgCAFQgMAXgHAjIgEAQQgHAcgPAgIgLAVQgGAMgHAMQgkA3geA5IgKAVIgTAvIgCAGIgDAHIABABQgWCJBqA0IgBABIAIACQAcAGAhAJIANAGQAhANAkAFQAeAFAdAHQAQAEAPACQAtAEAtABIgFA1Qh2gOiEgfgAFGO0QAKgdgBgkIAvACIgHBGIgxgHgAivEuIAAgBIANABgABIlwIADgFQiEljDplkQA5hSA4g7QguBNgOBTIgEAVQgJA2gVAwQgDAIgMAOQgLAOgbAJQgbAJgkBiQgjBiBIBaQBJBagDBdQgDBIg9BWQgUg2geg1g");
	this.shape_10.setTransform(281,169.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#6AD301").s().p("AJJGnIAHgMIAHgJIACgBIAEAGQAWAjgVAoIgCADIgBACQgkgcASgkgApnBuIAAgHQAAgJADgKQAFgOAMgOIAFgGIADgBQAVAdgCAgQgBAJgDAKQgDAKgGAKIgEAHQgbgWgDgYgAEwnlIAEgBQAuA+glBIIgGAIQhNg8BGhRg");
	this.shape_11.setTransform(333.9,159.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.lf(["#49C406","#FDE64D"],[0,1],0.1,-114.3,0,183.6).s().p("A/PyAMA+eAAAIAAaDIgNgSQgohogwhoQCPmykFmQQjAkVjAgKQiNgHiMCJIgQAQQg5A7g4BSQjrFjCGFhIgDAGQgQgcgRgbQiQjNiPgHQhpgFhqBmIgMAKQgqAsgqA9QidDtA+DsQgKAAgJgCQgNgGgNgCQgMgMgQgLIgSgKQgKgSgQgPQgggfgoAcQgJgsgKgKQhIhAhkAAQhmAAhHBAQgPAOgNAQQgagMgfAAQg6AAgpAnQgNAMgJAOQgKAPgFARIAAACQgFAQAAASQAAA3AqAnQApAmA6AAQAhAAAcgNQALAVAUARIALAJQh6A3h3BrQj2hEjrBPQnACUnGA9gA4yKWQAtAmA/AAQA+AAAtgmIAEgDQAxAWBAAAQBIAAAdghIAYAEIACAAIAKAAQAzAAAkgaQAkgaAAglIAAgIQgBgLgEgKIAKgCIABgBQAqgTAfiHIADgPIgHAOIAAAAQg9B9hMgQQgNgGgOgCQgMgMgQgLIgSgKQgKgSgPgPQghgfgqAcQgJgsgLgKQhHhAhlAAQhkAAhIBAQgQAOgMAQQgagMgfAAQg7AAgoAnQgOAMgIAOQgKAPgFARIgBACQgEAQAAASQABA3ApAnQAoAmA7AAQAhAAAcgNQALAVAUARgABiLvQATgCAQgFIgIARIgbgKgATqGlIgugIIEoAJIh2ABIgDAAIgBAAIgDAAQgYADgZAAQgkAAgogFg");
	this.shape_12.setTransform(200,115.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#65CA00").s().p("ALCTMIBeAeIAngIIAAAmQg8AMhEADgALBS3IiDgFIg+gBIhMgDQAQgTAegHQADgBADgEQAMgSAlAGQAPACAJgFQAFgCAGgBQBIgDBDAIQAMACAJAFIAGAEIAHAFQAIAEAFAFQANALARgBQAHAAAFADQAHAEACAOgAn0RCIB1AlICzglQAYguAKg0QAGgfABggQAEhtgviEIgYhHQgIiGi1hPQgqgSg0gQIgBgBIgMgBIhbgKQjfgbEngHIAfAAIAogBQA8gDBGg1IAGgEQAigbAmgnQALgMAJgNQAYglAJgxIABgSQAGg7gRhLQgKgtgRgyQgKgdgNgeIgUguQh3kBi5guQCQAHCPDQQASAbAQAbQAdA1AUA2QAYBAALBBQAKA9gBA9IgBANQgBAxgJAyQgIAogMAoIgGAVQB9EWA8EXQANgFAOgEQAGgBACgGQAUgeA+AJQAaAEAPgIQAIgEAKgBIBDgBQgPAtgMAuIglgBIhpgDIhCgCIAEAWQAJAiAAAdQABAkgKAeQgkBhinAVQh2AriWAHgAn1QoIilgFIhOgDIhegDQATgYAmgJQAFgBADgFQAPgWAtAHQAUADAMgGQAGgDAHgBQBagEBTAKQAPACAMAGIAGAFQAFAEAFADQAJAFAIAGQAPANAWAAQAIgBAHAEQAKAFAAASgAMuK9QgYgOgdgMIgcgLIglgMIgBAAQktgeELgGIBCgBIAGgBQAkgEApgZIAdgUIAACYQgLgJgOgHgAJ2hiQhVgEhUBSIgKAKQgwgUg4gQIgBgBQosg2JhgIQB7gHCbihQCbihikmPQikmPkMhCQDAAJC/EVQEFGQiOG1QAvBoAoBmIAOARIAAAiQhWiSh7gegADjguIADAAIgEABIABgBg");
	this.shape_13.setTransform(316.1,162.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#71E100").s().p("ANnTjIgBgVIBnADQgBgOgHgEQgGgDgGAAQgSABgMgLQgGgFgHgEIgIgFIgFgEQgKgFgMgCQhCgIhIADQgGABgFACQgJAFgPgCQglgGgMASQgDAEgDABQgfAHgPATIBLADIgEAzQgkgBgkgEQgMgBgNgEIgagGIgVgDQgdgFgagKIgLgEIgEgBQgYgHgUgFIgHgBIABgBQhVgpAShuIgBgBIACgGIACgEIAPglIAIgRIAWgoQAPgaAQgZIAKgRIABgBIAIgRQAMgaAGgWIADgNIADgMQAFgUAHgPQACgDgIgKQgHgKgQgeQgPgfA8hGQA9hFACg4QABgWgGgVQgKgigbghQgUgZgGgbQgHgdALgfQAVg7ARgFQAQgGAHgIQAHgIACgFQAMgdAFggIADgMQAIgzAcgtIAKgKQBUhQBUAEQB7AeBXCSIAAHnIgeAUQgoAZgkAEIgGABIhCABQkLAGEtAeIABAAIAlAMIAcALQAdAMAYAOQANAHAMAJIAAB1IgGgJIgCABQgqAwAtAkIAEgFIABAAIAAFZIgnAIgAG9PbQgMAOgFANQgMAgAgAZQADgCABgDIACgDQATgpgagkIgCABgAKaNFQgPARgDAQQgFASALARQAGAIAKAIIAEgEIAFgMQAGgPgBgPQgCgUgOgTIgCABgAKCLZQgqAxAuAkIADgFQAXgsgcglIgCABgAOuGKIgHAJIgHALQgSAkAkAcIABgBIACgEQAVgogWgjIgEgFIgCABgAKyDoIgBACQgoAvAtAkIAEgFQAWgrgbglIgBgBIgCABgAKCCOQgqAxAuAkIADgFQAXgrgcglIgCAAgAlPRZIgCgaICBAEQgBgSgJgFQgHgEgIABQgWAAgPgNQgIgGgJgFQgGgDgEgEIgGgFQgMgGgPgCQhTgKhaAEQgHABgGADQgMAGgUgDQgugHgPAWQgDAFgEABQgmAJgTAYIBeADIgGBAQgtgBgtgFQgPgCgQgEQgdgHgegFQgkgFghgNIgNgFQghgKgcgGIgIgBIABgCQhqg0AWiJIgBAAIADgIIACgGIATguIAKgVQAeg6Akg3QAHgMAGgMIALgVQAPggAHgcIAEgQQAHgiAMgYQACgFgJgMQgKgMgTgmQgKgUAPggQAMgbAegjIAKgMQBLhXADhGQABgXgGgXIgEgOIgHgTQgNgdgXgdQg3hBAbhKQAbhJAUgHQAUgHAJgKQAIgLADgGQAQgkAGgoIADgPQALg/Aig5IAMgMQBqhnBpAFQC5AuB3EBIAUAuQAMAeAKAdQASAyAKAtQARBLgGA7IgCASQgIAxgYAlQgJANgMAMQglAngjAbIgFAEQhGA1g8ADIgoABIgfAAQkoAHDfAbIBcAKIAMABIABABIgNAAIhsgDIhlgEIAiAGQAdAEAaAAQAUAAATgCIBRgBIANAAQA0AQAqASQC1BPAHCGIAZBHQAtCEgEBtQAAAggGAfQgKA0gYAuIiyAlgAg0OVQgKAMgGALQgTAiATAcQAHALANAKIAFgGIAEgJQAOgggJgeQgFgPgKgPIgDABgAtlMPQg0A8A5AtQADgCABgEQAcg2giguIgDABgAi0JiIgJANQglA1AzAoIAFgGQAXgtgUgoQgEgIgGgIIgDABgApQJTQg0A9A5AtIAFgGQAcg2gjgvIgDABgApuHMQgaAeABAbQABAaAdAXQADgCABgEIAIgQQAPgtgdgoIgDABgAj3ApIgFAGQgMAPgFANQgDAKAAAJIAAAHQADAYAbAWIAEgHQAGgKADgKQADgKABgJQACgggVgdIgDABgAoyigQg0A9A5AtIAFgGQAcg2gjguIgDAAgApukQQg0A9A5AtQADgDABgDQAdg2gjgvIgDABgACVPOQgBgdgIgiIgEgWIBEACIgIBVIgvgCgAg4EmIAHgVQAMgoAHgoQAJgyACgxIABgNQABg/gKg7QgLhBgYhAQA9hWABhIQADhdhHhaQhIhaAjhiQAkhiAbgJQAbgJALgOQAKgOADgIQAVgwAJg1IAEgVQAOhUAuhMIAQgQQCNiJCNAHQEMBCCkGPQCjGPiaChQibChh7AHQphAIIsA2IABABIkogJIAuAHQBEAJA5gGIADAAIAEgBIB2AAQA4AQAwASQgiAjgiAxQhJBvgNBwQgFAoADAnQAFA+AXA9QhGCOguCOIhCABQgKABgIAEQgPAIgbgEQg9gJgUAeQgEAGgGABQgPAEgMAFQg8kXh8kWgAC7D1QgUAXgIAXQgTA0A1ArQAEgEADgEQAUgngEgkQgEgfgVgdQgBAAgBAAQAAAAAAABQgBAAAAAAQgBAAAAABgACTBAQhGBSBMA8QAEgEACgEQAmhJgug+IgEABgAKHnuQhGBRBNA9IAGgJQAlhIgug+IgEABgADjr8QhGBRBMA9QAEgEADgFQAlhIgug+IgEABgACTuSQhGBRBMA9QAEgEACgFQAmhIgug+IgEABg");
	this.shape_14.setTransform(299.6,160.1);

	this.addChild(this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,400,300);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;